In [21]:
import numpy as np
import pandas as pd

data = pd.read_csv('data/MostStreamedArtists.csv')
data = pd.DataFrame(data)
data.head()

,#,Artist,Lead Streams,Feats,Tracks,1b,100m,10m,1m,Update
0,1,Drake,4.977530e+10,1.931858e+10,262,6,128,256,259,04.09.22
1,2,Bad Bunny,4.377569e+10,4.999271e+09,164,5,118,158,163,04.09.22
2,3,Ed Sheeran,3.780317e+10,2.758580e+09,239,10,62,177,216,05.09.22
3,4,The Weeknd,3.434841e+10,3.586149e+09,186,8,72,145,168,04.09.22
4,5,Justin Bieber,3.219848e+10,1.077093e+10,225,6,56,174,197,04.09.22

In [22]:
streamed_artist = data[['Lead Streams', '#']].dropna().head(10)

print(streamed_artist.dtypes)
streamed_artist.head()

Lead Streams    float64
#                 int64
dtype: object

   Lead Streams  #
0  4.977530e+10  1
1  4.377569e+10  2
2  3.780317e+10  3
3  3.434841e+10  4
4  3.219848e+10  5

In [23]:
n = streamed_artist.__len__()
x = streamed_artist['Lead Streams'].to_numpy()
y = streamed_artist['#'].to_numpy()

x = x.astype(np.int64)

print(f'n={n}')
print(f'x={x}')
print(f'y={y}')

n=10
x=[49775299233 43775691246 37803173410 34348409474 32198482081 32108092122
 32095003484 30191017275 29622222294 28219735162]
y=[ 1  2  3  4  5  6  7  8  9 10]